### PR TITLE
Updating the example to use devcontainer using Genie framework

### PR DESCRIPTION
**Pull request by azar-writes-code**
@Tpuljak 
### Julialang support #1364
Add Julia Sample Project with Genie.jl Framework  

---

#### **Problem Addressed**  
The repository previously lacked an example project for Julia, making it difficult for users of Daytona.io who prefer Julia to get started. This gap was noted in Issue #1364.

#### **Proposed Solution**  
This PR introduces a sample project for Julia using the Genie.jl framework. The project includes:  
- A basic web application scaffolded using Genie.jl.  
- A `devcontainer.json` configuration for a seamless development environment.  
- Clear documentation to guide users in setting up and running the project.  
-
Devcontainer

#### **Key Features**  
- **Genie.jl Integration**: Implements a simple web server showcasing how Julia can be used with Daytona.io.  
- **Dev Container Setup**: Preconfigured development environment for VS Code with Julia 1.11, ensuring compatibility and ease of use.  
- **Documentation**: Instructions for setup and usage included in the `README.md` file.  

#### **Testing & Verification**  
The project was tested in the following scenarios:  
1. Running locally with Julia 1.11 installed.  
2. Running inside the VS Code Dev Container with Docker.  

#### **Next Steps**  
Potential future enhancements:  
- Expand the project with an example demonstrating API routes or database integration.  
- Provide a similar example using Oxygen.jl for diversity.

---

Let me know if there are any suggestions or improvements to incorporate!  

Best regards,  
Azar M

### CODE REVIEW

**Comment by s-celles** [comment]
Hi @azar-writes-code 

I did a look at your PR. Your approach is different than mine providing a sample example with a web framework instead of a console application but I think we are both experimenting an other issue.

Are you also facing this?

```
> daytona create https://github.com/azar-writes-code/sample-julia
 WORKSPACE    | ✓ Request submitted
 WORKSPACE    | ✓ Creating workspace sample-julia (4159311ba74c)
 sample-julia | Creating project sample-julia
 sample-julia | Pulling image...
 sample-julia | Pulling from daytonaio/workspace-project
 sample-julia | Digest: sha256:2bbb1ea57364e2bba5d15c02a7d8b0cafd633fd1881ab6ab60ef2ed95aec6edc
 sample-julia | Status: Image is up to date for daytonaio/workspace-project:latest
 sample-julia | Image pulled successfully
 sample-julia | Cloning into '/workdir/4159311ba74c-sample-julia'...
 sample-julia | Reading devcontainer configuration...
time="2024-11-27T20:28:20+01:00" level=fatal msg="failed to create workspace: container exited with status 2"
```

Best regards

PS : maybe we should have a kind of tree of samples in Daytona? 

```
Samples/
├─ Alpine
├─ Debian
├─ Ubuntu
├─ C
├─ C++
├─ C#
├─ Go
├─ Java
├─ PHP
├─ Python/
│  ├─ Python console app
│  ├─ Python web app (Flask)
├─ Ruby
├─ Julia/
│  ├─ Julia console app
│  ├─ Julia web app (Genie.jl)

```

**Comment by azar-writes-code** [comment]
Hey @s-celles,

I agree buddy, but the description regarding the issue states "
Maybe providing a similar example for Julia (probably with Genie.jl or Oxygen.jl) should be considered
" 

So, I thought to choose one out of both frameworks based on its popularity.

If @Tpuljak thinks we can go with @s-celles approach, I'll be happy to make changes.

Regards,
Azar M

**Comment by s-celles** [comment]
Thanks @azar-writes-code 
What is your opinion about using devcontainer-features ? https://github.com/JuliaLang/devcontainer-features
instead of julia:1.11.1-bullseye (so we could have `juliaup` also available?)
Automatic code formatting is also an interesting feature to have automatically enabled (I love this feature!)

**Comment by azar-writes-code** [comment]
> Thanks @azar-writes-code What is your opinion about using devcontainer-features ? https://github.com/JuliaLang/devcontainer-features instead of julia:1.11.1-bullseye (so we could have `juliaup` also available?) Automatic code formatting is also an interesting feature to have automatically enabled (I love this feature!)

I've reviewed this, and it seems the project hasn't been maintained recently, with its last update being over two years ago. According to JuliaLang, version 1.11.1 is the latest release and addresses several critical security vulnerabilities.

Since we operate in the open-source space, where many people rely on our code, it's crucial to uphold high standards. For this reason, I opted to use the latest image @s-celles .

Thanks for the kind words, mate! 😊

**Comment by s-celles** [comment]
I totally share your opinion about high standard of quality. That's why I provided a sample project with unit tests and auto formatting.
To my understanding the devcontainer features simply doesn't need updating as it rely on juliaup which can download any julia version including latest and lts version where security vulnabilities have been fixed.

**Comment by azar-writes-code** [comment]
> I totally share your opinion about high standard of quality. That's why I provided a sample project with unit tests and auto formatting. To my understanding the devcontainer features simply doesn't need updating as it rely on juliaup which can download any julia version including latest and lts version where security vulnabilities have been fixed.

I opted to use an official Julia Docker image for this implementation. Specifically, I utilized the latest Julia image available in the Dockerfile. This approach was chosen to align with best practices and ensure compatibility by leveraging the maintained and up-to-date official image.
@s-celles

**Comment by mojafa** [comment]
@azar-writes-code this PR fails DCO check

**Comment by azar-writes-code** [comment]
> @azar-writes-code this PR fails DCO check

Oh, I'll fix this @mojafa , thanks for pointing out :)

**Comment by azar-writes-code** [comment]
> @azar-writes-code this PR fails DCO check

Hi @mojafa,
I've signed off my commit and ensured all the checks passed.

**Comment by mojafa** [comment]
@azar-writes-code also, please close this PR and move it to this new repo: https://github.com/daytonaio/sample-julia-genie

We'll have both samples of Julia. So also pleasse include the framework example in the daytona index. I'll comment there as well

**Comment by azar-writes-code** [comment]
> @azar-writes-code also, please close this PR and move it to this new repo: https://github.com/daytonaio/sample-julia-genie
> 
> We'll have both samples of Julia. So also pleasse include the framework example in the daytona index. I'll comment there as well

Sure @mojafa. Closing this PR and moving this to https://github.com/daytonaio/sample-julia-genie
Btw, do you have any name suggestion to make changes on daytona index

**Comment by mojafa** [comment]
@azar-writes-code please close this PR

**Comment by azar-writes-code** [comment]
Done @mojafa

**Pull request closed without merging**
